version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8080:80" # Change this line to use port 8080
    volumes:
      - ./build:/usr/share/nginx/html
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80" # Change this line to use port 8080